package com.wuwind.undercover.db.litepal;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import org.litepal.crud.LitePalSupport;

/**
 * Entity mapped to table "GAME".
 */
public class Game extends LitePalSupport implements Cloneable {

    private Long id;
    private Long wordId;
    private Integer count;
    private Integer normal;
    private Integer undercover;
    private Integer blank;
    private Integer audience;
    private String sequence;
    private String out;
    private Integer finish;//1开局2平民获胜3卧底获胜

    public Game() {
    }

    public Game(Long id) {
        this.id = id;
    }

    public Game(Long id, Long wordId, Integer count, Integer normal, Integer undercover, Integer blank, Integer audience, String sequence, String out, Integer finish) {
        this.id = id;
        this.wordId = wordId;
        this.count = count;
        this.normal = normal;
        this.undercover = undercover;
        this.blank = blank;
        this.audience = audience;
        this.out = out;
        this.sequence = sequence;
        this.finish = finish;
    }

    @Override
    public Game clone() {
        try {
            return (Game) super.clone();
        } catch (CloneNotSupportedException e) {
            e.printStackTrace();
        }
        return null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getWordId() {
        return wordId;
    }

    public void setWordId(Long wordId) {
        this.wordId = wordId;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Integer getNormal() {
        return normal;
    }

    public void setNormal(Integer normal) {
        this.normal = normal;
    }

    public Integer getUndercover() {
        return undercover;
    }

    public void setUndercover(Integer undercover) {
        this.undercover = undercover;
    }

    public Integer getBlank() {
        return blank;
    }

    public void setBlank(Integer blank) {
        this.blank = blank;
    }

    public Integer getAudience() {
        return audience;
    }

    public void setAudience(Integer audience) {
        this.audience = audience;
    }

    public String getOut() {
        return out;
    }

    public void setOut(String out) {
        this.out = out;
    }

    public String getSequence() {
        return sequence;
    }

    public void setSequence(String sequence) {
        this.sequence = sequence;
    }

    public Integer getFinish() {
        return finish == null ? 0 : finish;
    }

    public void setFinish(Integer finish) {
        this.finish = finish;
    }

}
