package com.wuwind.undercover.db.litepal;

import org.litepal.crud.LitePalSupport;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "WORD".
 */
public class Word extends DbSupport {

    private String w1;
    private String w2;

    public Word() {
    }

    public String getW1() {
        return w1;
    }

    public void setW1(String w1) {
        this.w1 = w1;
    }

    public String getW2() {
        return w2;
    }

    public void setW2(String w2) {
        this.w2 = w2;
    }

}
