package com.wuwind.undercover.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wuwind.undercover.db.Word;
import com.wuwind.undercover.db.Game;

import com.wuwind.undercover.db.WordDao;
import com.wuwind.undercover.db.GameDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wordDaoConfig;
    private final DaoConfig gameDaoConfig;

    private final WordDao wordDao;
    private final GameDao gameDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
        wordDaoConfig.initIdentityScope(type);

        gameDaoConfig = daoConfigMap.get(GameDao.class).clone();
        gameDaoConfig.initIdentityScope(type);

        wordDao = new WordDao(wordDaoConfig, this);
        gameDao = new GameDao(gameDaoConfig, this);

        registerDao(Word.class, wordDao);
        registerDao(Game.class, gameDao);
    }
    
    public void clear() {
        wordDaoConfig.clearIdentityScope();
        gameDaoConfig.clearIdentityScope();
    }

    public WordDao getWordDao() {
        return wordDao;
    }

    public GameDao getGameDao() {
        return gameDao;
    }

}
