package com.wuwind.undercover.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "GAME".
 */
@Entity
public class User implements Cloneable {

    @Id(autoincrement = true)
    private Long id;
    private String wxId;
    private String wxName;
    private String wxPhoto;
    private String users;
    private Long gameId;
    private String words;
    private String wordIS;
    private Integer ready;
    private Integer uOut;
    private String updateTime;

    @Generated
    public User(Long id, String wxId, String wxName, String wxPhoto, String users, Long gameId, String words, String wordIS, Integer ready, Integer uOut, String updateTime) {
        this.id = id;
        this.wxId = wxId;
        this.wxName = wxName;
        this.wxPhoto = wxPhoto;
        this.users = users;
        this.gameId = gameId;
        this.words = words;
        this.wordIS = wordIS;
        this.ready = ready;
        this.uOut = uOut;
        this.updateTime = updateTime;
    }

    @Generated
    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    @Override
    public User clone() {
        try {
            return (User) super.clone();
        } catch (CloneNotSupportedException e) {
            e.printStackTrace();
        }
        return null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWxId() {
        return wxId;
    }

    public void setWxId(String wxId) {
        this.wxId = wxId;
    }

    public String getWxName() {
        return wxName;
    }

    public void setWxName(String wxName) {
        this.wxName = wxName;
    }

    public String getWxPhoto() {
        return wxPhoto;
    }

    public void setWxPhoto(String wxPhoto) {
        this.wxPhoto = wxPhoto;
    }

    public String getUsers() {
        return users;
    }

    public void setUsers(String users) {
        this.users = users;
    }

    public Long getGameId() {
        return gameId;
    }

    public void setGameId(Long gameId) {
        this.gameId = gameId;
    }

    public String getWords() {
        return words;
    }

    public void setWords(String words) {
        this.words = words;
    }

    public String getWordIS() {
        return wordIS;
    }

    public void setWordIS(String wordIS) {
        this.wordIS = wordIS;
    }

    public Integer getReady() {
        return ready;
    }

    public void setReady(Integer ready) {
        this.ready = ready;
    }

    public Integer getuOut() {
        return uOut;
    }

    public void setuOut(Integer uOut) {
        this.uOut = uOut;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
}
